	/*
 * Author : BASSAM_MAHMOUD_
 * Layer  : MCAl
 * SWC    : PORT
 * Version: 1.0
 * Created: JUN/18/2024
 */
 
#ifndef PORT_CONFIG_H_
#define PORT_CONFIG_H_

/*OPTIONS,				 0 FOR INPUT
 *						 1 FOR OUTPUT
 */
#define PORTA_PIN0_DIR   0
#define PORTA_PIN1_DIR   0
#define PORTA_PIN2_DIR   0
#define PORTA_PIN3_DIR   0
#define PORTA_PIN4_DIR   0
#define PORTA_PIN5_DIR   0
#define PORTA_PIN6_DIR   0
#define PORTA_PIN7_DIR   0

#define PORTB_PIN0_DIR   0
#define PORTB_PIN1_DIR   0
#define PORTB_PIN2_DIR   0
#define PORTB_PIN3_DIR   0
#define PORTB_PIN4_DIR   0
#define PORTB_PIN5_DIR   0
#define PORTB_PIN6_DIR   0
#define PORTB_PIN7_DIR   0

#define PORTC_PIN0_DIR   0
#define PORTC_PIN1_DIR   0
#define PORTC_PIN2_DIR   0
#define PORTC_PIN3_DIR   0
#define PORTC_PIN4_DIR   0
#define PORTC_PIN5_DIR   0
#define PORTC_PIN6_DIR   0
#define PORTC_PIN7_DIR   0

#define PORTD_PIN0_DIR   0
#define PORTD_PIN1_DIR   0
#define PORTD_PIN2_DIR   0
#define PORTD_PIN3_DIR   0
#define PORTD_PIN4_DIR   1
#define PORTD_PIN5_DIR   1
#define PORTD_PIN6_DIR   0
#define PORTD_PIN7_DIR   1

/*OPTIONS,		 				0 FOR LOW(FLOUTING WHILE PIN INPUT)
 *								1 FOR HIGH(PULLEDUP WHILE PIN INPUT)
 */
#define PORTA_PIN0_INIT_VALUE   0
#define PORTA_PIN1_INIT_VALUE   0
#define PORTA_PIN2_INIT_VALUE   0
#define PORTA_PIN3_INIT_VALUE   0
#define PORTA_PIN4_INIT_VALUE   0
#define PORTA_PIN5_INIT_VALUE   0
#define PORTA_PIN6_INIT_VALUE   0
#define PORTA_PIN7_INIT_VALUE   0

#define PORTB_PIN0_INIT_VALUE   0
#define PORTB_PIN1_INIT_VALUE   0
#define PORTB_PIN2_INIT_VALUE   0
#define PORTB_PIN3_INIT_VALUE   0
#define PORTB_PIN4_INIT_VALUE   0
#define PORTB_PIN5_INIT_VALUE   0
#define PORTB_PIN6_INIT_VALUE   0
#define PORTB_PIN7_INIT_VALUE   0

#define PORTC_PIN0_INIT_VALUE   0
#define PORTC_PIN1_INIT_VALUE   0
#define PORTC_PIN2_INIT_VALUE   0
#define PORTC_PIN3_INIT_VALUE   0
#define PORTC_PIN4_INIT_VALUE   0
#define PORTC_PIN5_INIT_VALUE   0
#define PORTC_PIN6_INIT_VALUE   0
#define PORTC_PIN7_INIT_VALUE   0

#define PORTD_PIN0_INIT_VALUE   0
#define PORTD_PIN1_INIT_VALUE   0
#define PORTD_PIN2_INIT_VALUE   0
#define PORTD_PIN3_INIT_VALUE   0
#define PORTD_PIN4_INIT_VALUE   0
#define PORTD_PIN5_INIT_VALUE   0
#define PORTD_PIN6_INIT_VALUE   0
#define PORTD_PIN7_INIT_VALUE   0

#endif
 