/*
 * Author : Bassam Mahmoud
 * Layer  : HAL
 * SWC    : LEDMRX
 * Version: 1.0
 * Created: NOV/23/2023
 */

#ifndef LEDMRX_CONFIG_H_
#define LEDMRX_CONFIG_H_

#define	LEDMRX_ROWS_NUM			8
#define LEDMRX_COLS_NUM			8

/* PLEASE DEFINE LED MATRIX COLUMNS & ROWS PINS IN ORDER */
#define LEDMRX_ROWS_PINS		{{GPIO_PORTB,0},{GPIO_PORTB,1},{GPIO_PORTB, 2},{GPIO_PORTB, 3},{GPIO_PORTB, 4},{GPIO_PORTB, 5},{GPIO_PORTB, 6},{GPIO_PORTB, 7}}
#define LEDMRX_COLS_PINS		{{GPIO_PORTA,7},{GPIO_PORTA,9},{GPIO_PORTA,10},{GPIO_PORTA,11},{GPIO_PORTA,12},{GPIO_PORTA,13},{GPIO_PORTA,14},{GPIO_PORTA,15}}

/* PLEASE ENTER DISPLAY SHIFTING SPEED (0 FOR MAX)*/
#define LEDMRX_SPEED			5

#endif
