/*
 * Author : BASSAM_MAHMOUD_
 * Layer  : HAL
 * SWC	  : SSD
 * Version: 1.0
 * Created: JUN/6/2024
 */

#ifndef SSD_CONFIG_H_
#define SSD_CONFIG_H_			


/*CHOOSE COMMON TYPE: 
 *OPTIONS,								SSD_COM_CATH FOR COMMON CATHOD
 * 										SSD_COM_ANOD FOR COMMON ANOD
 */			
#define SSD_COM_TYPE					SSD_COM_ANOD

/*CHOOSE NUMBER OF SEV SEG DISPLAYS:
 *NOTE: DISPLAYS NUMBER MUST NOT EXCEED 6
 *
 */
#define SSD_DISPLAYS_NUM				4

/*SET DESPLAYS DATA PINS:
 *OPTIONS,								PORT,PIN_NUMBER
 */
#define SSD_DATA_PIN0					GPIO_u8PORTC,0
#define SSD_DATA_PIN1					GPIO_u8PORTC,1
#define SSD_DATA_PIN2					GPIO_u8PORTC,2
#define SSD_DATA_PIN3					GPIO_u8PORTC,3
#define SSD_DATA_PIN4					GPIO_u8PORTC,4
#define SSD_DATA_PIN5					GPIO_u8PORTC,5
#define SSD_DATA_PIN6					GPIO_u8PORTC,6

/*SET DESPLAYS ENABLE PINS:
 *OPTIONS,								PORT,PIN_NUMBER
 *										NULL IF NOT USED
 */		
#define SSD_ENABLE_PIN0					GPIO_u8PORTD,0
#define SSD_ENABLE_PIN1					GPIO_u8PORTD,1
#define SSD_ENABLE_PIN2					GPIO_u8PORTD,2
#define SSD_ENABLE_PIN3					GPIO_u8PORTD,3
#define SSD_ENABLE_PIN4					NULL
#define SSD_ENABLE_PIN5					NULL


#endif